### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by inf3rno** [kernkonzept/l4re-core#2]
Sorry for bothering you, it's 5 am and I could not sleep the whole night, so I read about l4 kernels. I am just curious about what is missing from l4re to run pytorch or tensorflow for example? I am not entirely sure I understand the whole concept here, I try to learn about how operating systems work and as far as I understand l4re would give a lot more performance compared to linux in exchange for less features. But I don't fully understand what features and if I really require them, when all I need is running a program fast and deliver the results somehow to a different computer that runs the HTTP or websocket server. Probably it is an oversimplification of the whole thing, but I am not that educated in the topic. Can you explain me?

**Comment by jermar** [comment]
I am not familiar with either pytorch or tensorflow. Generally, L4Re is a framework of basic components that are useful for creating e.g. virtualization scenarios with different instances of (Linux) VMs. As such, it is not a full-fledged OS itself, but can be used for building one provided you can source the missing components from somewhere else or write them from scratch.

Let me briefly theorize on what is needed to achieve your goal. From the components that are available here on GH, you can use l4virtio to write a VIRTIO net client and connect it via virtio-net to a Linux VM. Your client will probably need a networking stack to sit on top of the virtual NIC, which you'll need to source from somewhere. If you need this to work on real hw, you'll also need to provide the respective drivers (for example from the rumpkernel project or by writing them from scratch). The easiest is to use a VM with a guest OS which already comes with all these components, but then you also get all the other stuff that your application doesn't need. There are different approaches with different trade-offs.

I am going to close this ticket now as this is a question rather than an actual issue.

**Comment by inf3rno** [comment]
@jermar Thanks! Both are machine learning libraries, they need Python and GPU. I am just trying to estimate how hard would be filling the gap between these libraries and what L4Re currently offers. But it would have been simpler to ask what I need to run a hellow world in C for example using L4Re on real hardware? I guess the mentioned libraries only need a GPU driver on top of it. Is there a forum where I can ask this or maybe a documentation or article that contains this info?
